FROM node:22

# 2️⃣ Set the working directory inside the container
WORKDIR /usr/src/app

# 5️⃣ Copy the rest of the project files
# COPY ./src . or 
#  FOR EVERYTHING ELSE
COPY . . 
# 3️⃣ Install dependencies
RUN npm install


RUN npm run build

RUN rm -rf ./src
   


# 7️⃣ Expose port 3001 (the NestJS default port)
EXPOSE 3001


# 4️⃣ Build the project
CMD ["npm", "run", "start:prod"]